# Generated by Django 4.2.7 on 2026-04-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_alter_itempesanan_id_alter_pesanan_id_and_more'),
        ('toko', '0002_itempesanan_harga_satuan_pesanan_id_pesanan_and_more'),
    ]

    operations = [
    ]
