# Generated by Django 4.2.7 on 2026-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_merge_20260417_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar2',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar3',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar4',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
